---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pac-demo
  annotations:
    # updated by git push
    # The event we are targeting as seen from the webhook payload
    # this can be an array too, i.e: [pull_request, push]
    pipelinesascode.tekton.dev/on-event: "[[pull_request, push]]"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "[tektonci]"

    # Fetch the git-clone task from hub, we are able to reference later on it
    # with taskRef and it will automatically be embedded into our pipeline.
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/task-1: "[.tekton/tasks/maven.yaml]"
    pipelinesascode.tekton.dev/task-2: "[.tekton/tasks/dependencyreport.yaml]"
    pipelinesascode.tekton.dev/task-3: "[.tekton/tasks/s2ijava11.yaml]"
    pipelinesascode.tekton.dev/task-4: "[.tekton/tasks/updatedeployment.yaml]"
    pipelinesascode.tekton.dev/task-5: "[.tekton/tasks/argocdsyncandwait.yaml]"

    # Use maven task from hub
    #
    # pipelinesascode.tekton.dev/task-1: "maven"

    # You can add more tasks by increasing the suffix number, you can specify them as array to have multiple of them.
    # browse the tasks you want to include from hub on https://hub.tekton.dev/
    #
    # pipelinesascode.tekton.dev/task-2: "[curl, buildah]"

    # How many runs we want to keep.
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    # The variable with brackets are special to Pipelines as Code
    # They will automatically be expanded with the events from Github.
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: workspace
      - name: maven-settings
#      - name: basic-auth
    tasks:
      - name: source-clone
        taskRef:
         name: git-clone
         kind: ClusterTask
        workspaces:
         - name: output
           workspace: workspace
        params:
         - name: url
           value: https://github.com/gamagnolo/spring-petclinic
         - name: revision
           value: main
         - name: depth
           value: "0"
         - name: subdirectory
           value: spring-petclinic
         - name: deleteExisting
           value: "true"
      - name: unit-tests
        taskRef:
          name: maven
        runAfter:
          - source-clone
        workspaces:
         - name: source
           workspace: workspace
         - name: maven-settings
           workspace: maven-settings
        params:
        - name: GOALS
          value: ["package", "-f", "spring-petclinic"]
      - name: code-analysis
        taskRef:
          name: maven
        runAfter:
          - source-clone
        workspaces:
          - name: source
            workspace: workspace
          - name: maven-settings
            workspace: maven-settings
        params:
        - name: GOALS
          value:
          - install
          - sonar:sonar
          - -f
          - spring-petclinic
          - -Dsonar.host.url=http://sonarqube:9000
          - -Dsonar.userHome=/tmp/sonar
          - -DskipTests=true
      - name: dependency-report
        taskRef:
          name: dependency-report
        runAfter:
          - source-clone
        workspaces:
          - name: source
            workspace: workspace
          - name: maven-settings
            workspace: maven-settings
        params:
        - name: SOURCE_DIR
          value: spring-petclinic
      - name: release-app
        taskRef:
          name: maven
        runAfter:
          - code-analysis
          - unit-tests
          - dependency-report
        workspaces:
          - name: source
            workspace: workspace
          - name: maven-settings
            workspace: maven-settings
        params:
        - name: GOALS
          value:
          - deploy
          - -f
          - spring-petclinic
          - -DskipTests=true
          - -DaltDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-releases/
          - -DaltSnapshotDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-snapshots/
      - name: build-image
        taskRef:
          name: s2i-java-11
        runAfter:
          - release-app
        params:
        - name: TLSVERIFY
          value: "false"
        - name: MAVEN_MIRROR_URL
          value: http://nexus:8081/repository/maven-public/
        - name: PATH_CONTEXT
          value: spring-petclinic/target
        - name: IMAGE_NAME
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/spring-petclinic
        - name: IMAGE_TAG
          value: latest
        workspaces:
        - name: source
          workspace: workspace
      - name: image-scan
        runAfter:
          - build-image
        taskRef:
          name: rox-image-scan
          kind: ClusterTask
        params:
        - name: image
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/spring-petclinic
        - name: rox_api_token
          value: roxsecrets
        - name: rox_central_endpoint
          value: roxsecrets
        - name: output_format
          value: table
        - name: image_digest
          value: $(tasks.build-image.results.IMAGE_DIGEST)
      - name: image-check
        runAfter:
          - build-image
        taskRef:
          name: rox-image-check
          kind: ClusterTask
        params:
        - name: image
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/spring-petclinic
        - name: rox_api_token
          value: roxsecrets
        - name: rox_central_endpoint
          value: roxsecrets
        - name: image_digest
          value: $(tasks.build-image.results.IMAGE_DIGEST)
      - name: deploy-check
        runAfter:
          - build-image
        taskRef:
          name: rox-deployment-check
          kind: ClusterTask
        params:
        - name: GIT_REPOSITORY
          value: https://github.com/gamagnolo/spring-petclinic-config
        - name: rox_api_token
          value: roxsecrets
        - name: rox_central_endpoint
          value: roxsecrets
        - name: file
          value: deployment.yaml
        - name: deployment_files_path
          value: app
        workspaces:
        - name: workspace
          workspace: workspace
      - name: update-deployment
        runAfter:
          - image-scan
          - image-check
          - deploy-check
        taskRef:
          name: git-update-deployment
        params:
        - name: GIT_REPOSITORY
          value: https://github.com/gamagnolo/spring-petclinic-config
        - name: CURRENT_IMAGE
          value: quay.io/siamaksade/spring-petclinic:latest
        - name: NEW_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/spring-petclinic
        - name: NEW_DIGEST
          value: "$(tasks.build-image.results.IMAGE_DIGEST)"
        - name: KUSTOMIZATION_PATH
          value: environments/dev
        workspaces:
        - name: workspace
          workspace: workspace
      - name: wait-application
        taskRef:
          name: argocd-task-sync-and-wait
        runAfter:
          - update-deployment
        params:
        - name: application-name
          value: dev-spring-petclinic
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: maven-settings
    configMap:
       name: maven-settings
